apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/christianvogt-tenant/test-app/devfile-sample@sha256:616979cfd975cb71457a1a129ae7021c859ad6bc969d160ef09c41c76a88013d
        name: my-nodejs
        resources: {}
status: {}
